# Generated by Django 5.1.6 on 2026-02-08 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0003_player_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='at_bats',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='player',
            name='hits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
