# Generated by Django 5.1.6 on 2026-02-08 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0004_player_at_bats_player_hits'),
    ]

    operations = [
        migrations.CreateModel(
            name='Minor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('city', models.CharField(max_length=25)),
            ],
        ),
    ]
