# Generated by Django 5.1.6 on 2026-02-10 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0006_prospect'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gaa_Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('rating', models.IntegerField(default=50)),
            ],
        ),
    ]
