# Generated by Django 5.1.6 on 2026-02-14 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0007_gaa_team'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaa_team',
            name='losses',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gaa_team',
            name='wins',
            field=models.IntegerField(default=0),
        ),
    ]
