# Generated by Django 5.1.6 on 2026-02-14 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0008_gaa_team_losses_gaa_team_wins'),
    ]

    operations = [
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
