# Generated by Django 5.1.6 on 2026-02-15 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0009_news'),
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('conference_name', models.CharField(max_length=100)),
            ],
        ),
    ]
