# Generated by Django 5.1.6 on 2026-02-15 23:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0010_conference'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCAA_TEAM',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=100)),
                ('conference_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conference_assigned', to='league.conference')),
            ],
        ),
    ]
