# Generated by Django 5.1.6 on 2026-02-16 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0011_ncaa_team'),
    ]

    operations = [
        migrations.CreateModel(
            name='NCAA_Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(max_length=100)),
                ('last', models.CharField(max_length=100)),
                ('GP', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('GS', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('TOT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FGM', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FGA', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FG_PERCENT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Three_PT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Three_PTA', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('Three_PT_PERCENT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FTA', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('FT_PERCENT', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('PTS', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('AVG', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
