# Generated by Django 5.1.6 on 2026-02-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0012_ncaa_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(max_length=100)),
                ('total_shares', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
