# Generated by Django 5.1.6 on 2026-02-17 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0013_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
    ]
