# Generated by Django 6.0.1 on 2026-03-07 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0015_excelupload_alter_conference_id_alter_gaa_team_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_num', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
    ]
