# Generated by Django 6.0.1 on 2026-03-26 03:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('league', '0017_event_eventdate'),
    ]

    operations = [
        migrations.CreateModel(
            name='All_Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('position', models.CharField(choices=[('C', 'Catcher'), ('1B', 'First Base'), ('2B', 'Second Base'), ('3B', 'Third Base'), ('SS', 'Shortstop'), ('LF', 'Left Field'), ('CF', 'Center Field'), ('RF', 'Right Field'), ('DH', 'Designated Hitter')], max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('opponent', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PlayerGameStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ba', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.game')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='league.all_player')),
            ],
        ),
    ]
